fluendo/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('flutodo.urls', namespace="flutodo")),
]

flutodo/urls.py
from django.conf.urls import url

from . import views

app_name = 'flutodo'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^login/$', views.login, name="login"),
    url(r'^register/$', views.register, name="register"),
    url(r'^logout/$', views.logout, name="logout"),

    url(r'^todos/$', views.todos, name="todos"),
    url(r'^create/$', views.create, name='create'),
    url(r'^delete/(?P<pk>[0-9]+)$', views.delete, name='delete'),
    url(r'^detail/(?P<pk>[0-9]+)$', views.detail, name='detail'),
    url(r'^done/(?P<pk>[0-9]+)$', views.done, name='done'),

    url(r'^api/todos/(?P<pk>[0-9]+)$', views.todo_list, name='todo_list'),
    url(r'^api/todo/$', views.todo_post, name='todo_post'),
    url(r'^api/todo/(?P<pk>[0-9]+)$', views.todo_api, name='todo_api'),

]

flutodo/models.py
from __future__ import unicode_literals

from django.utils import timezone
from django.db import models

from django.contrib.auth.models import User

class Todo(models.Model):
    title = models.CharField(max_length=255, null=True)
    created = models.DateTimeField('created', default=timezone.now)
    done = models.BooleanField(default=False)
    user = models.ForeignKey(User)

flutodo/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Todo


class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ('title','done')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')

flutodo/views.py
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.http import HttpResponse

from rest_framework import serializers
from rest_framework.parsers import JSONParser
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from .models import Todo
from .forms import UserForm, TodoForm
from .serializers import TodoSerializer


def index(request):
        return render(request, 'flutodo/index.html')

def login(request):
    if request.method == "POST":
        userlogin = request.POST['login']
        password = request.POST['password']
        user = authenticate(username=userlogin, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect('flutodo:todos')
        else:
            pass

    return render(request, 'flutodo/login.html')


def register(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(request.POST['password'])
            new_user.save()
            messages.success(request, 'user ok you may login now')
            return redirect('flutodo:login')
        else:
            messages.error(request, 'register error: check your input')
    else:
        form = UserForm()

    return render(request, 'flutodo/register.html', {'form': form})


def logout(request):
    auth_logout(request)
    return redirect('flutodo:index')


def todos(request):
    if request.user is not None and request.user.is_authenticated:
        todos = Todo.objects.filter(user=request.user).order_by('created')
        context = {'todos': todos}
        return render(request, 'flutodo/todos.html', context)
    else:
        return redirect('flutodo:index')

def create(request):
    if request.method == "POST":
        form = TodoForm(request.POST)
        if form.is_valid():
            todo = form.save(commit=False)
            todo.user = request.user
            todo.save()
            return redirect('flutodo:todos')
        else:
            return HttpResponse("error")
    else:
        form = TodoForm()

    return render(request, 'flutodo/create.html', {'form': form})

def detail(request, pk):
    todo_item = Todo.objects.get(pk=pk)
    if request.method == "POST":
        form = TodoForm(request.POST, instance=todo_item)
        if form.is_valid():
            todo = form.save(commit=False)
            todo.user = request.user
            todo.save()
            return redirect('flutodo:todos')
        else:
            return HttpResponse("error")
    else:
        form = TodoForm(instance=todo_item)

    return render(request, 'flutodo/detail.html', {'form': form})


def delete(request, pk):
    todo_item = Todo.objects.get(pk=pk)
    todo_item.delete()
    messages.success(request, 'todo item %s has been deleted' % todo_item.title)
    return redirect('flutodo:todos')


def done(request, pk):
    todo_item = Todo.objects.get(pk=pk)
    todo_item.done = not todo_item.done
    todo_item.save()
    return redirect('flutodo:todos')


@csrf_exempt
@api_view(['GET'])
def todo_list(request, pk):
    user = User.objects.filter(pk=int(pk))
    todo_list = Todo.objects.filter(user=user)
    todo_serializer = TodoSerializer(todo_list, many=True)
    return JsonResponse(todo_serializer.data, safe=False)


@csrf_exempt
@api_view(['POST'])
def todo_post(request):
    if request.method == 'POST':
        serializer = TodoSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serilizer.errors, status=status.HTTP_400_BAD_REQUEST)


@csrf_exempt
@api_view(['GET', 'PUT', 'DELETE'])
def todo_api(request, pk):
    try:
        todo = Todo.objects.get(pk=pk)
    except:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = TodoSerializer(todo)
        return Response(serializer.data)

    elif request.method == 'PUT':
        serializer = TodoSerializer(todo, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serilizer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        todo.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

flutodo/templates/flutodo/base.html
{% load staticfiles %}

<html>

<head>

<title>fluendo todo webapp</title>

<link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'flutodo/flutodo.css' %}" />


</head>

<body>

    {% if user.is_authenticated %}

        <p>Hello, {{ user.username }}.</p>

        <ul>
            <li><a href="{% url 'flutodo:logout' %}">logout</a></li>
        </ul>

    {% else %}

        <p> Hello, welcome to flutodo list manager</p>
        <p> please <a href="{% url 'flutodo:login' %}">login</a> 
        or <a href="{% url 'flutodo:register' %}">register</a> to manage your flutodo list</p>


    {% endif %}


    {% if messages %}
    <ul class="messagelist">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}



{% block content %}
{% endblock %}

</body>

flutodo/templates/flutodo/create.html
{% extends 'flutodo/base.html' %}

{% block content %}

<form method="post">
    {{ form.as_p }}
    <input type="submit" value="add"/>
    {% csrf_token %}
</form>

{% endblock %}

flutodo/templates/flutodo/detail.html
{% extends 'flutodo/base.html' %}

{% block content %}

<form method="post">
    {{ form.as_p }}
    <input type="submit" value="update"/>
    {% csrf_token %}
</form>

{% endblock %}

flutodo/templates/flutodo/index.html
{% extends 'flutodo/base.html' %}

{% block content %}
{% endblock %}

flutodo/templates/flutodo/login.html
{% extends 'flutodo/base.html' %}

{% block content %}

<form method="post">
    <input type="text" name="login" placeholder="user"/>
    <input type="password" name="password" placeholder="password"/>
    <input type="submit" value="login"/>
    {% csrf_token %}
</form>

{% endblock %}

flutodo/templates/flutodo/register.html
{% extends 'flutodo/base.html' %}

{% block content %}

<form method="post">
    <input type="text" name="username" placeholder="user"/>
    <input type="password" name="password" placeholder="password"/>
    <input type="submit" value="register"/>
    {% csrf_token %}
</form>

{% endblock %}

flutodo/templates/flutodo/todos.html
{% extends 'flutodo/base.html' %}
{% load static %}

{% block content %}

    <p>
    <a href="{% url 'flutodo:create' %}" class="addlink">add new todo item</a>
    </p>

    {% if todos %}
        <ul>
            {% for todo in todos %}
            <li>
                {{todo.title}}
                <a href="{% url 'flutodo:detail' todo.pk %}" class="changelink" title="edit"></a>
                <a href="{% url 'flutodo:delete' todo.pk %}" class="deletelink" title="del"></a>
                {% if todo.done %}
                    <img src="{% static 'admin/img/icon-yes.svg' %}" alt="done" />
                {% else %}
                    <a href="{% url 'flutodo:done' todo.pk %}" title="completed?">
                        <img src="{% static 'admin/img/icon-unknown.svg' %}" alt=completed?" />
                    </a>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p> no todo items</p>
    {% endif %}

{% endblock %}